version: "2"

services:
  puissance4-incineroar-theme:
    container_name: puissance4-incineroar-theme
    image: node:10-alpine
    user: "node"
    working_dir: /home/node/app
    command: "/bin/sh -c \"npm install && npm start -s\""
    env_file:
      - .env
    volumes:
      - ".:/home/node/app"
    labels:
      - "traefik.http.routers.puissance4-incineroar-theme.rule=Host(`puissance4.cet1bot.app`)"
      - traefik.http.services.puissance4-incineroar-theme.loadbalancer.server.port=8080
      - traefik.http.routers.puissance4-incineroar-theme.middlewares=https-redirectscheme
      - "traefik.http.routers.puissance4-incineroar-theme-secure.rule=Host(`puissance4.cet1bot.app`)"
      - traefik.http.routers.puissance4-incineroar-theme-secure.tls=true
      - traefik.http.routers.puissance4-incineroar-theme-secure.tls.certresolver=sslresolver
    networks:
      - backend

networks:
  backend:
    external:
      name: backend
