version: "2"

services:
  cet1bot-app-back:
    container_name: cet1bot-app-back
    image: node:10-alpine
    user: "node"
    working_dir: /home/node/app
    command: "/bin/sh -c \"npm install && npm start -s\""
    env_file:
      - .env
    volumes:
      - ".:/home/node/app"
    labels:
      - "traefik.http.routers.cet1bot-app-back.rule=Host(`puissance4.cet1bot.app`)"
      - traefik.http.services.cet1bot-app-back.loadbalancer.server.port=8080
      - traefik.http.routers.cet1bot-app-back.middlewares=https-redirectscheme
      - "traefik.http.routers.cet1bot-app-back-secure.rule=Host(`puissance4.cet1bot.app`)"
      - traefik.http.routers.cet1bot-app-back-secure.tls=true
      - traefik.http.routers.cet1bot-app-back-secure.tls.certresolver=sslresolver
    networks:
      - backend

networks:
  backend:
    external:
      name: backend
